# Generated by Django 2.2.5 on 2019-10-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='correo',
            field=models.EmailField(default='SOME STRING', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entidad',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombre',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='defaultpass', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
